version: '3.9'

services:
  db:
    restart: always
    build:
      context: ./
      dockerfile: ./schema/Dockerfile
    networks:
      new:
        aliases:
          - database
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - new
    command: sh -c "./wait-for-postgres.sh db; ./app"
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

networks:
  new: