basePath: /
definitions:
  common.CompanyCreateRequest:
    properties:
      building:
        properties:
          city_id:
            description: id города должен существовать в БД
            type: integer
          house:
            type: integer
          point:
            description: в формате "(1.00234567, -90.00876211)"
            type: string
          street_id:
            description: id улицы с привязкой к городу должен существовать в БД
            type: integer
        type: object
      name:
        type: string
      phones:
        items:
          properties:
            number:
              description: номер телефона
              type: string
          type: object
        type: array
      rubric:
        items:
          properties:
            id:
              description: id рубрики должен существовать в БД
              type: integer
          type: object
        type: array
    type: object
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:80
info:
  contact: {}
  description: API Server for company catalog
  title: Catalog App API
  version: 0.0.1
paths:
  /api/company/:
    post:
      consumes:
      - application/json
      description: Creating company with minimal required data
      operationId: createCompany
      parameters:
      - description: Company created info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/common.CompanyCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: id
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Create company
      tags:
      - Company
swagger: "2.0"
